"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const {execFileSync}=require("node:child_process"),{createHash}=require("node:crypto"),{chromium,webkit}=require("playwright");
const root=path.resolve(__dirname,"../tests/fixtures"),repo=path.resolve(__dirname,"..");
const guard=require("../tests/helpers/self-profile-a-only.cjs");
const manifest=guard.contract,rows=manifest.files;
const hash=s=>createHash("sha256").update(s).digest("hex"),member=p=>"app/tennis-note-member-app/"+p;
const git=(sha,p)=>execFileSync("git",["show",`${sha}:${p}`],{cwd:repo,encoding:"utf8",maxBuffer:12e6}).replace(/\r\n/g,"\n");
const sources=new Map();let checks=0;
for(const row of rows){let s=git(manifest.base,row.path);assert.equal(hash(s),row.beforeHash);for(const p of row.patches){assert.equal(s.split(p.before).length,2);s=s.replace(p.before,()=>p.after);}assert.equal(hash(s),row.afterHash);if(row.path.endsWith(".js"))new vm.Script(s);let inverse=s;for(const p of [...row.patches].reverse()){assert.equal(inverse.split(p.after).length,2);inverse=inverse.replace(p.after,()=>p.before);}assert.equal(hash(inverse),row.beforeHash);const actual=guard.undoRelease(row.path,fs.readFileSync(path.join(repo,row.path),"utf8"));assert.equal(actual,s,"actual source matches verified A-only projection");sources.set(row.path,actual);checks++;}
const read=p=>sources.get(p)||guard.undoRelease(p,fs.readFileSync(path.join(repo,p),"utf8"));
function fn(s,name,indent=""){const m=[...s.matchAll(new RegExp("^"+indent+"(?:async )?function "+name+"\\([^\\n]*\\)[^{]*\\{[\\s\\S]*?^"+indent+"}","gm"))];assert.equal(m.length,1,"exact function "+name);return m[0][0];}
const auth=read(member("data/auth.js")),enroll=read(member("actions/enrollment.js")),actions=read(member("actions/profile.js")),view=read(member("views/profile.js"));
const originalSignup=fn(git(manifest.base,member("data/auth.js")),"persistIdentityProfile"),candidateSignup=fn(auth,"persistIdentityProfile");
const originalBody=originalSignup.slice(originalSignup.indexOf(" {\n")+3);
assert(candidateSignup.endsWith(originalBody),"entire original signup body remains byte identical");checks++;
for(const name of ["readSavedSelfProfileExactly","updateMemberProfileOnServer","saveProfileInfo","saveProfileInfoOnce"]){assert.equal(hash(fn(actions,name)),manifest.functionHashes[member("actions/profile.js")+"#"+name],"approved own-profile function "+name);checks++;}
for(const name of ["renderProfile","renderNtrpSurvey"]){assert.equal(hash(fn(view,name)),manifest.functionHashes[member("views/profile.js")+"#"+name],"approved draft function "+name);checks++;}
for(const name of ["request","selectRows","performSelectCurrentProfile"]){assert.equal(hash(fn(read("app/shared/tennisnote-data-client.js"),name,"  ")),manifest.functionHashes["app/shared/tennisnote-data-client.js#"+name],"approved transport function "+name);checks++;}
for(const marker of ["tn_save_my_signup_profile","signupProfileOperation","requireSignupReadback","expectedProfileId","expectedAuthUserId","tn_book_makeup_entitlement","tn_request_future_participant_absence","tn_admin_record_monthly_settlement_manual_payment"]){for(const row of rows)assert.equal(read(row.path).split(marker).length,git(manifest.base,row.path).split(marker).length,"excluded delta "+marker);checks++;}
const FixedDate=class extends Date{constructor(...a){super(...(a.length?a:["2026-10-09T00:00:00Z"]));}static now(){return new Date("2026-10-09T00:00:00Z").getTime();}};
function legacyRuntime(source,scenario){const calls=[],c={Date:FixedDate,identityPrivacyVersion:"synthetic-privacy",normalizeIdentityText:x=>String(x||"").trim(),normalizeIdentityPhone:x=>String(x||"").replace(/\D/g,""),requireVerifiedIdentityPhone:async()=>{calls.push("verify");},hasLiveMemberSession:()=>scenario!=="offline",retryTransientNetwork:async f=>{calls.push("retry");return f();},applySavedIdentity:p=>calls.push({applied:p}),window:{TennisNoteDataClient:{rpc:async(n,p)=>{calls.push({rpc:n,parameters:p});if(scenario==="rpc-error")throw Error("synthetic-rpc-error");const r={ok:true,profile:{name:p.target_real_name,phone:"",role:"member"},linkStatus:"approval_pending"};return scenario==="array"?[r]:r;}}}};vm.createContext(c);vm.runInContext(source,c);return {c,calls};}
async function legacyChecks(){const input={realName:"합성 이름",nickname:"합성 닉네임",phone:["010","0000","0000"].join(""),birthYear:1990,neighborhood:"합성 동네",gender:"prefer_not"};for(const scenario of ["ok","array","rpc-error","offline"]){const a=legacyRuntime(originalSignup,scenario),b=legacyRuntime(candidateSignup,scenario);let ar,br;try{ar=await a.c.persistIdentityProfile(input);}catch(e){ar={error:e.message};}try{br=await b.c.persistIdentityProfile(input);}catch(e){br={error:e.message};}assert.ok(JSON.stringify(ar)===JSON.stringify(br),"legacy reply parity "+scenario);assert.ok(JSON.stringify(a.calls)===JSON.stringify(b.calls),"legacy exact RPC7 args/retry/approval parity "+scenario);checks+=2;}
  for(const blank of [true,false]){const states=[];for(const s of [git(manifest.base,member("actions/enrollment.js")),enroll]){const c={Date:FixedDate,state:{profile:{name:"합성 이름",nickname:"합성 닉네임",phone:"synthetic-saved-phone",profileCompletedAt:"synthetic-completion",privacyConsentVersion:"synthetic-privacy",privacyConsentedAt:"synthetic-consent"},member:null},normalizeIdentityText:x=>x||"",normalizeIdentityPhone:x=>x||"",identityPrivacyVersion:"synthetic-privacy"};vm.createContext(c);vm.runInContext(fn(s,"applySavedIdentity"),c);c.applySavedIdentity(blank?{phone:""}:{});states.push(c.state.profile);}assert.ok(JSON.stringify(states[0])===JSON.stringify(states[1]),"legacy default applySavedIdentity preserved");checks++;}
}
const browserSetup=`
const $=s=>document.querySelector(s);
const state={dataMode:"live",liveProfileId:"synthetic-self",member:{role:"member",status:"active",authUserId:"synthetic-auth",profileId:"synthetic-self"},profile:{name:"합성 이름",nickname:"합성 닉네임",phone:"",birthYear:1990,gender:"prefer_not",serverRevision:"2026-10-09T00:00:00Z",hand:"오른손",backhand:"투핸드 백핸드",startedAt:"2000-01-01",goal:"합성 목표",styleMemo:"합성 메모",selfNtrp:"3",coachNtrp:"측정 전",ntrpSurvey:{},photoDataUrl:""},ticketHistory:[]};
let profileInfoSaving=false,ntrpCheckSaving=false,profilePhoneExpectedPhone="",profilePhoneEditorOwner=null;
let selfProfileStyleOperation={fingerprint:"",key:"",parameters:null},profilePhoneSaveOperation={fingerprint:"",key:""};
let fixtureRows=[],fixtureCalls=[],fixtureReads=[],fixturePending=null,fixtureDefer=true,fixtureDuplicate=false,fixtureOffline=false,fixtureFailure=false,fixtureRevision=0;
const fixtureReceipts=new Map();
const identityPrivacyVersion="synthetic-privacy",hasLiveMemberSession=()=>true;
const ntrpReferences=[],ntrpQuickLevels=[],ntrpSurveyQuestions=[];
const syncNtrpResultFromCoach=()=>{},renderProfileAvatar=()=>{},renderDiscountCouponWallet=()=>{},renderPushNotificationSettings=()=>{},renderAccountDeletionSettings=()=>{},renderTickets=()=>{},saveSnapshot=()=>{},exportNtrpRequest=()=>{},canUseCoachMode=()=>false;
const setNicknameStatus=(id,message)=>{const n=$("#"+id);if(n)n.textContent=message;};
const showToast=message=>{$("#appToast").textContent=message;},closeAppSheet=id=>{if(!window.TennisNoteBottomSheet.close(id,{history:false,immediate:true}))throw Error("fixture_sheet_close_failed");};
const collectNtrpSurvey=()=>({level:"3",answers:{rally:3}});
window.TennisNoteInputGuard={markSaved:()=>{}};
window.TennisNoteDataClient={getSession:()=>({access_token:"synthetic-session",user:{id:"synthetic-auth"}}),rpc:async(name,p)=>{
fixtureCalls.push({name,parameters:JSON.parse(JSON.stringify(p))});if(name!=="tn_save_my_verified_profile_phone")throw Error("unexpected_rpc");
if(fixtureFailure)throw new TypeError("Failed to fetch");
if(!fixtureReceipts.has(p.target_operation_key)){fixtureRevision++;const target={...p.target_profile};delete target.expected_revision;
const row={id:"synthetic-self",role:state.member.role,status:"active",updated_at:"2026-10-09T00:00:0"+fixtureRevision+"Z",...target};
fixtureReceipts.set(p.target_operation_key,{ok:true,profileContract:"atomic-self-profile/1",styleSaved:true,phoneVerified:false,profile:row});}
const reply=fixtureReceipts.get(p.target_operation_key);fixtureRows=[JSON.parse(JSON.stringify(reply.profile))];
if(fixtureDefer)await new Promise(r=>{fixturePending=r;});return JSON.parse(JSON.stringify(reply));},selectRows:async(table,options)=>{
fixtureReads.push({table,options:JSON.parse(JSON.stringify(options))});if(fixtureOffline)throw Error("fresh_read_required");return fixtureDuplicate?[...fixtureRows,...fixtureRows]:JSON.parse(JSON.stringify(fixtureRows));}};
function fixtureEdit(){profilePhoneExpectedPhone=state.profile.phone;profilePhoneEditorOwner={...phoneVerificationOwner(),revision:state.profile.serverRevision};if(!window.TennisNoteBottomSheet.open("profileEditorSheet",{history:false,initialFocus:false}))throw Error("fixture_sheet_open_failed");}
`;
const actualFunctions=[fn(read(member("domain/identity.js")),"normalizeIdentityText"),fn(read(member("domain/identity.js")),"normalizeIdentityPhone"),fn(read(member("domain/identity.js")),"formatIdentityPhone"),...(["phoneVerificationOwner","phoneVerificationOwnerCurrent","phoneVerificationRequestCurrent","phoneVerificationControls"].map(n=>fn(read(member("forms/members.js")),n))),fn(enroll,"applySavedIdentity"),candidateSignup,actions,fn(view,"renderProfile"),fn(view,"renderNtrpSurvey")];
new vm.Script(browserSetup+"\n"+actualFunctions.join("\n"));
async function browserChecks(){const results=[];for(const [name,engine]of[["chromium",chromium],["webkit",webkit]]){const browser=await engine.launch({headless:true});try{for(const width of [390,768,1366])for(const theme of ["light","dark"]){const page=await browser.newPage({viewport:{width,height:900},colorScheme:theme}),errors=[];let external=0;
page.on("pageerror",e=>errors.push(e.message));await page.route("**/*",route=>{if(route.request().url()==="https://r2-a-only.invalid/")return route.fulfill({contentType:"text/html",body:"<body></body>"});external++;return route.abort();});await page.goto("https://r2-a-only.invalid/");assert.equal(await page.evaluate(()=>isSecureContext&&typeof crypto.randomUUID==="function"),true);checks++;
const sheet=await page.evaluate(html=>{const d=new DOMParser().parseFromString(html,"text/html"),s=d.querySelector("#profileEditorSheet");if(!s)throw Error("actual_profile_sheet_missing");s.hidden=false;return s.outerHTML;},read(member("index.html")));
await page.setContent('<main class="app-shell">'+sheet+'</main><div id="appToast"></div>');
const memberStyle=await page.addStyleTag({content:read(member("styles.css"))});for(const p of ["app/shared/tennisnote-ui-foundation.css","app/shared/tennisnote-bottom-sheet.css","app/shared/tennisnote-issue-reporter.css"])await page.addStyleTag({content:read(p)});await page.evaluate(()=>{document.documentElement.dataset.tennisnoteSurface="member";});
await page.evaluate(t=>{document.documentElement.dataset.theme=t;},theme);
// 실제 앱과 같은 열기/닫기 lifecycle을 사용한다. hidden 해제만으로는 닫힌 패널을 클릭하는 race가 된다.
await page.addScriptTag({content:read("app/shared/tennisnote-bottom-sheet.js")});
await page.addScriptTag({content:browserSetup+"\n"+actualFunctions.join("\n")});assert.deepEqual(errors,[]);await page.evaluate(()=>{fixtureEdit();$("#profileRealNameInput").value=state.profile.name;$("#profileNicknameInput").value=state.profile.nickname;$("#profileHand").value="왼손";$("#profileBackhand").value="원핸드 백핸드";$("#profileStartedAt").value=state.profile.startedAt;$("#profileSelfNtrp").value="3";$("#saveProfileInfo").addEventListener("click",saveProfileInfo);for(let i=0;i<3;i++)renderProfile();});
assert.equal(await page.locator("#profileHand").inputValue(),"왼손");checks++;
await page.waitForFunction(()=>$("#profileEditorSheet").dataset.tnSheetState==="open"&&$("#profileEditorSheet").dataset.tnSheetInputReady==="true");
await page.locator("#saveProfileInfo").scrollIntoViewIfNeeded();
const clickGeometry=await page.evaluate(()=>{const s=$("#profileEditorSheet"),b=$("#saveProfileInfo"),r=b.getBoundingClientRect(),p=s.querySelector("[data-tn-sheet-panel]"),hit=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return {state:s.dataset.tnSheetState,ready:s.dataset.tnSheetInputReady,transform:getComputedStyle(p).transform,height:r.height,inViewport:r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth,exactHit:hit===b||b.contains(hit)};});
assert.equal(clickGeometry.state,"open");assert.equal(clickGeometry.ready,"true");assert.equal(clickGeometry.transform,"matrix(1, 0, 0, 1, 0, 0)");assert(clickGeometry.height>=44);assert.equal(clickGeometry.inViewport,true);assert.equal(clickGeometry.exactHit,true);checks+=6;
await page.locator("#saveProfileInfo").click();try{await page.waitForFunction(()=>fixturePending!==null);}catch(e){const diagnostic=await page.evaluate(()=>({rpcCount:fixtureCalls.length,saveLocked:profileInfoSaving,noticeCode:$("#appToast").textContent?"NOTICE_PRESENT":"NO_NOTICE"}));throw Error("fixture_save_pending_missing "+JSON.stringify({engine:name,width,theme,diagnostic,pageErrors:errors}));}assert.deepEqual(errors,[]);
const pending=await page.evaluate(async()=>({calls:fixtureCalls.length,duplicateResult:await saveProfileInfo(),saveDisabled:$("#saveProfileInfo").disabled,ntrpDisabled:$("#requestNtrpCheck").disabled,identityReadOnly:$("#profileRealNameInput").readOnly,identityDisabled:$("#profileRealNameInput").disabled}));
assert.equal(pending.calls,1);assert.equal(pending.duplicateResult,false);assert.equal(pending.saveDisabled,true);assert.equal(pending.ntrpDisabled,true);assert.equal(pending.identityReadOnly,true);assert.equal(pending.identityDisabled,false);checks+=6;
await page.evaluate(()=>{fixtureDefer=false;fixturePending();fixturePending=null;});await page.waitForFunction(()=>$("#profileEditorSheet").hidden);
const saved=await page.evaluate(()=>({hand:state.profile.hand,role:state.member.role,rpc:fixtureCalls[0].name,fresh:fixtureReads.length===1&&fixtureReads[0].options.requireFresh===true&&fixtureReads[0].options.requireCurrentSession===true&&fixtureReads[0].options.retryAuth===false,filters:Object.keys(fixtureReads[0].options.filters),history:state.ticketHistory.length,identityUnlocked:!$("#profileRealNameInput").readOnly}));
assert.equal(saved.hand,"왼손");assert.equal(saved.role,"member");assert.equal(saved.rpc,"tn_save_my_verified_profile_phone");assert.equal(saved.fresh,true);assert.deepEqual(saved.filters,["id"]);assert.equal(saved.history,1);assert.equal(saved.identityUnlocked,true);checks+=7;
await page.evaluate(()=>{renderProfile();fixtureEdit();});assert.equal(await page.locator("#profileHand").inputValue(),"왼손");checks++;
await page.evaluate(async()=>{fixtureDuplicate=true;$("#profileHand").value="오른손";await saveProfileInfo();});
const failed=await page.evaluate(()=>({open:!$("#profileEditorSheet").hidden,draft:$("#profileHand").value,oldSaved:state.profile.hand,calls:fixtureCalls.length,history:state.ticketHistory.length,unlocked:!$("#saveProfileInfo").disabled,notice:$("#appToast").textContent.includes("결과를 확인하지 못했습니다")}));
assert.equal(failed.open,true);assert.equal(failed.draft,"오른손");assert.equal(failed.oldSaved,"왼손");assert.equal(failed.calls,2);assert.equal(failed.history,1);assert.equal(failed.unlocked,true);assert.equal(failed.notice,true);checks+=7;
await page.evaluate(async()=>{fixtureDuplicate=false;await saveProfileInfo();});
const replay=await page.evaluate(()=>({same:JSON.stringify(fixtureCalls[1].parameters)===JSON.stringify(fixtureCalls[2].parameters),receipts:fixtureReceipts.size,hand:state.profile.hand,history:state.ticketHistory.length,noSignup:fixtureCalls.every(x=>x.name==="tn_save_my_verified_profile_phone")}));
assert.equal(replay.same,true);assert.equal(replay.receipts,2);assert.equal(replay.hand,"오른손");assert.equal(replay.history,2);assert.equal(replay.noSignup,true);checks+=5;
await page.evaluate(()=>{renderProfile();fixtureEdit();});const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,font:parseFloat(getComputedStyle($("#profileHand")).fontSize),touch:$("#saveProfileInfo").getBoundingClientRect().height}));await memberStyle.evaluate((e,s)=>{e.textContent=s;},git(manifest.base,member("styles.css")));const baselineFont=await page.locator("#profileHand").evaluate(e=>parseFloat(getComputedStyle(e).fontSize));await memberStyle.evaluate((e,s)=>{e.textContent=s;},read(member("styles.css")));assert.equal(layout.overflow,false);assert.equal(layout.font,baselineFont,"existing desktop/mobile type scale unchanged");if(width<=1024)assert(layout.font>=16,"canonical mobile foundation contract");assert(layout.touch>=44);assert.deepEqual(errors,[]);assert.equal(external,0);checks+=6;
if(process.env.TENNISNOTE_SELF_PROFILE_SCREENSHOTS)await page.screenshot({path:path.join(root,`synthetic-${name}-${width}-${theme}.png`),fullPage:true});results.push({engine:name,width,theme,result:"PASS",fontPx:layout.font,baselineFontPx:baselineFont,touchHeightPx:layout.touch,overflow:layout.overflow});await page.close();}}finally{await browser.close();}}
return results;}
(async()=>{await legacyChecks();const results=await browserChecks();process.stdout.write(JSON.stringify({kind:"r2-a-only-focused/1",result:"PASS",checks,contexts:results.length,results,productPaths:rows.length,inventoryHash:manifest.inventoryHash,legacySignupBodyPreserved:true,legacyScalar7RetryApprovalParity:true,canonicalSelfFunctions:true,freshExactSelfRead:true,duplicateClickRpc:0,logicalReplayExtraOperation:0,dbClients:0,externalRequests:0,productWrites:0,actualDevices:"NOT_VERIFIED",prodActualSave:"NOT_EXECUTED"}));})().catch(e=>{process.stderr.write(String(e.stack));process.exitCode=1;});
